### ISSUE TITLE
Fix: Device 별 UI 버그 수정

### ISSUE THREAD

**Issue by ima9ine4** [KOBOT-13/cliving-front#83]
**✍ Description**
Play Store 등록 심사 이전에 Device별, UI를 재확인하고 app flow를 따라가는 중에 발생하는 버그를 수정합니다.

@ima9ine4 담당 화면 
- calendar_screen
- mypage_screen
- record_screen
- video_player_screen

@rktlskan021 담당 화면
- login_screen
- join_screen
- camera_screen

**Todo**
- [ ] 기기별 overflow 현상이 일어나지 않도록 UI 수정
- [ ] 기기별 일부 content가 hidden 되지 않도록 UI 수정
- [ ] 작업 도중 발생하는 에러 해결
